#!/usr/bin/env python3
"""Copy approved contours and fixed eye fits, never animation frames, into Swift."""
import argparse, json, pathlib, re, subprocess, tempfile
root = pathlib.Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--kit', type=pathlib.Path, required=True, metavar='PATH',
                    help='path to the approved animation kit (not needed for normal builds)')
kit = parser.parse_args().kit.expanduser().resolve()
if not kit.is_dir():
    parser.error(f'--kit is not a directory: {kit}')
required_files = ['geometry-manifest.json', 'src/official-motion.ts'] + [
    f'src/bloub/{name}.ts' for name in
    ('skins', 'eyefit', 'profiles', 'shape', 'math', 'expressions', 'face', 'states', 'decor')
]
for relative_path in required_files:
    if not (kit / relative_path).is_file():
        parser.error(f'--kit is missing required file: {relative_path}')
source = (kit/'src/official-motion.ts').read_text()
def constant(name):
    return json.loads(re.search(r'const '+name+r':[^=]+= (\{.*\})\n', source).group(1))
manifest=json.loads((kit/'geometry-manifest.json').read_text())
with tempfile.TemporaryDirectory(prefix='grokoo-native-data-') as temp:
    dst=pathlib.Path(temp)
    for item in (kit/'src').rglob('*.ts'):
        target=dst/item.relative_to(kit/'src'); target.parent.mkdir(parents=True,exist_ok=True)
        target.write_text(re.sub(r"from '([^']+)'", lambda m: "from '"+m.group(1)+".ts'",item.read_text()))
    (dst/'extract.mjs').write_text("""import {SHAPES} from './bloub/skins.ts';
import {decalageDesYeux} from './bloub/eyefit.ts';
console.log(JSON.stringify(Object.fromEntries(SHAPES.map(s=>[s.id,{radii:s.radii,offsets:Object.fromEntries(['neutre','blase','somnolent'].map(e=>[e,decalageDesYeux(s.radii,'idle',e)]))}]))));
""")
    rest=json.loads(subprocess.check_output(['node','--experimental-transform-types',str(dst/'extract.mjs')],text=True))
value={'motion':constant('GEOMETRY'),'eyeContours':constant('EYE_CONTOURS'),'status':manifest['statusShapes'],'rest':rest}
text='''// Generated by scripts/generate-native-motion-data.py from the approved 2026-09-18 kit.
// Contours / fixed geometry only. Animation is sampled by native Swift code.
import Foundation

enum NativeMotionData {
    static let json = #"""
'''+json.dumps(value,separators=(',',':'))+'\n"""#\n}\n'
(root/'Grokoo/Rendering/NativeMotionData.swift').write_text(text)
print('Generated NativeMotionData.swift:',len(text),'bytes; 8 shapes, 8 eye contours, 24 fixed eye fits')
